[build]
{% if target == "riscv32ec-unknown-none-elf" -%}
target = "riscv32ec-unknown-none-elf.json"
{%- elsif target == "riscv32imfc-unknown-none-elf" -%}
target = "riscv32imfc-unknown-none-elf.json"
{%- else -%}
target = "{{ target }}"
{%- endif %}

[target."{{ target }}"]
runner = "wlink -v flash --enable-sdi-print --watch-serial"

{% if target == "riscv32ec-unknown-none-elf" or target == "riscv32imfc-unknown-none-elf" -%}
[unstable]
build-std = ["core"]
{% endif -%}