{% if mcu_family == "ch32v003" or mcu_family == "ch641" -%}
[build]
target = "riscv32ec-unknown-none-elf.json"
{%- else -%}
[build]
target = "{{ target }}"
{%- endif %}

[target."{{ target }}"]
runner = "wlink -v flash --enable-sdi-print --watch-serial"

{% if mcu_family == "ch32v003" or mcu_family == "ch641" -%}
[unstable]
build-std = ["core"]
{% endif %}
