{% if mcu_family == "ch32v003" %}
[build]
target = "riscv32ec-unknown-none-elf.json"
{% else %}
[build]
target = "{{ target }}"
{% endif %}

[target."{{ target }}"]
runner = "wlink -v flash --enable-sdi-print --watch-serial"

{% if mcu_family == "ch32v003" %}
[unstable]
build-std = ["core"]
{% endif %}
